### ISSUE TITLE
Qt@4 doesn't build on macOS 10.14

### ISSUE THREAD

**Issue by pjessesco** [cartr/homebrew-qt4#62]
Here is error log : 

    src/corelib/tools/qvarlengtharray.h:49:10: fatal error: 'new' file not found

El Capitan patch seems applied. Is it WIP, or no plans to support it?

**Comment by cartr** [comment]
Could you please run `brew config`, `brew doctor`, and `brew install -v cartr/qt4/qt@4` and paste the output into a Gist so I can take a look at it?

**Comment by pjessesco** [comment]
Here it is : https://gist.github.com/pjessesco/6b03049bc11e5e64b6ceb51b0c6c3f2f
